name: cdk pipeline demo CI

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::471112851791:role/github.to.aws.oicd
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: install aws cdk
      run: sudo npm install -g aws-cdk

    - name: cdk synth
      run: cdk synth

    - name: cdk bootstrap
      run: cdk bootstrap

    - name: cdk deploy
      run: cdk deploy --require-approval never