# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: cdk pipeline demo CI

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write # This is required for requesting the JWT


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::471112851791:role/github.to.aws.oicd
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: install aws cdk
      run: sudo npm install -g aws-cdk

    - name: cdk synth
      #working-directory: ./cdk-pipeline-demo
      run: cdk synth

    - name: cdk bootstrap
      #working-directory: ./cdk-pipeline-demo
      run: cdk bootstrap

    - name: cdk deploy
      #working-directory: ./cdk-pipeline-demo
    #  env:
    #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: cdk deploy